import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./page";
import {
  FacebookIcon,
  InstagramIcon,
  MailIcon,
  TwitterIcon,
  XIcon,
  YoutubeIcon,
} from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#ebece7] flex flex-col h-screen`}
      >
        <Navbar />
        <div className="flex-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}

export function Footer() {
  return (
    <footer className="bg-[#f2f2f2] p-4">
      <div className="max-w-4xl mx-auto flex flex-col items-center justify-between">
        <div className="flex items-center">
          <nav>
            <ul className="flex text-sm divide-x-2 flex-wrap">
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Corporate info
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  About us
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Contact us
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Blog
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Fraud awareness
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Report a security bug
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Investor relations
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Careers
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  WU foundation
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Intellectual property
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Online Privacy Statement
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Terms & Conditions
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Cookie Information
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Cookie Settings
                </a>
              </li>
              <li>
                <a
                  className="text-gray-600 text-[10px] px-1 hover:text-gray-800"
                  href="#"
                >
                  Sitemap
                </a>
              </li>
            </ul>
          </nav>
        </div>

        <div className="flex">
          <div className="max-w-7xl mx-auto mt-4">
            <p className="text-xs text-gray-600 text-[11px]">
              © 2023 Western Union Holdings, Inc. All Rights Reserved <br />The
              Western Union Online Service is offered by Western Union
              International Bank GmbH in conjunction with Western Union
              International Limited. Western Union International Bank GmbH,
              trading as Western Union International Bank is licensed by the
              Financial Markets Authority (Österreichische Finanzmarktaufsicht)
              in Austria.
            </p>
          </div>
          <div className="flex flex-col items-center">
            <div className="text-sm text-gray-600 text-[10px] mr-4">
              Follow us on
            </div>
            <div className="flex space-x-3 items-center">
              <FacebookIcon className="text-[#5091b5] h-6 w-6" fill="#5091b5"/>
              <YoutubeIcon className="text-white h-8 w-8" fill="#5091b5" strokeWidth={0.5}/>
              <InstagramIcon className="text-[#5091b5] h-6 w-6" />
              <TwitterIcon className="text-[#5091b5] text-[10px] h-6 w-6" />
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
